project:
  type: website
  output-dir: docs

website:
  title: "Deep Policy Lab"
  image: "/files/images/deeplab.png"
  description: "Deep Energy and Climate Policy Lab: Data Driven, Evidence based, Energy, Environmental, and Climate Policy; Deep analysis, Deep insights, for Deep decarbonization. Alias: DEEP Lab, DEEP Energy Lab, DEEP Climate Lab. Key words: Deep energy systems, Deep decarbonization, Deep modeling, Deep policy, Energy and climate policy, Energy Systems, Energy policy, Climate policy, Energy transition."
 
  navbar:
    background: "#05336B"
    foreground: "#FFFFFF"
    left:
      - text: About
        href: about.qmd
      - text: News
        href: news.qmd
      - text: Events
        href: events.qmd
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Projects
        href: projects.qmd 
      - text: Publications
        href: publications.qmd
      - text: Resources
        href: resources.qmd
      - text: Support
        href: support.qmd  
      - text: 中文
        href: cn.qmd        
    right:
      - icon: github
        href: https://github.com/deeppolicylab
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/deeppolicylab.bsky.social
        target: _blank
  page-navigation: true
  page-footer: 
    center: "[Deep Policy Lab](http://deeppolicylab.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # left: "[Deep Policy Lab](http://deeppolicylab.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # right:  
    #   - icon: github
    #     href: https://github.com/deeppolicylab
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app/profile/deeppolicylab.bsky.social
    #     target: _blank
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/deeppolicylab/deeppolicylab.github.io
#  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true 
#  card-style: summary      
  site-url: "http://deeppolicylab.github.io"
  google-analytics:
    tracking-id: "G-TEC97F8RGK"
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true 



